[package]
name = "abc433e"
version = "0.1.0"
edition = "2021"

[dependencies]
# ac-library-rs.workspace = true
# once_cell.workspace = true
# static_assertions.workspace = true
# varisat.workspace = true
# memoise.workspace = true
# argio.workspace = true
# bitvec.workspace = true
# counter.workspace = true
# hashbag.workspace = true
# pathfinding.workspace = true
# recur-fn.workspace = true
# indexing.workspace = true
# amplify.workspace = true
# amplify_derive.workspace = true
# amplify_num.workspace = true
# easy-ext.workspace = true
# multimap.workspace = true
# btreemultimap.workspace = true
# bstr.workspace = true
# az.workspace = true
# glidesort.workspace = true
# tap.workspace = true
# omniswap.workspace = true
# multiversion.workspace = true
# num.workspace = true
# num-bigint.workspace = true
# num-complex.workspace = true
# num-integer.workspace = true
# num-iter.workspace = true
# num-rational.workspace = true
# num-traits.workspace = true
# num-derive.workspace = true
# ndarray.workspace = true
# nalgebra.workspace = true
# alga.workspace = true
# libm.workspace = true
# rand.workspace = true
# getrandom.workspace = true
# rand_chacha.workspace = true
# rand_core.workspace = true
# rand_hc.workspace = true
# rand_pcg.workspace = true
# rand_distr.workspace = true
# petgraph.workspace = true
# indexmap.workspace = true
# regex.workspace = true
# lazy_static.workspace = true
# ordered-float.workspace = true
# ascii.workspace = true
# permutohedron.workspace = true
# superslice.workspace = true
# itertools.workspace = true
# itertools-num.workspace = true
# maplit.workspace = true
# either.workspace = true
# im-rc.workspace = true
# fixedbitset.workspace = true
# bitset-fixed.workspace = true
proconio.workspace = true
# text_io.workspace = true
# rustc-hash.workspace = true
# smallvec.workspace = true

[dev-dependencies]
cli_test_dir.workspace = true
